name: fromNull
version: '${project.version}'
main: me.kso4more.fromnull.FromNull
api-version: '1.20'
commands:
  vaccine:
    description: Open the menu inventory
  task:
      description: Open the emerald inventory
  virus:
    description: Spread virus
    usage: /<command> <entity name>
    permission: fromNull.virus
  lobby:
    description: Open or close the door of lobby
    permission: fromNull.lobby
  confirmed:
    description: Return number of confirmed cases
  vaccineCoverage:
    description: Return vaccine coverage
